#!/bin/bash

set -x

DOCKER_HUB_REPO_NAME=${DOCKER_HUB_REPO_NAME:-docker}

# build the graphite_exporter
(
	cd graphite-exporter
	docker build -t ${DOCKER_HUB_REPO_NAME}/docker-test-install-from-repo-graphite-exporter .
	docker push ${DOCKER_HUB_REPO_NAME}/docker-test-install-from-repo-graphite-exporter
)

# Build all test images
for img in $(find images -type f -name Dockerfile)
do
	dir=$(dirname $img)
	(
		cd $dir
		image_name=${DOCKER_HUB_REPO_NAME}/docker-test-install-from-repo-on-$(basename $dir)
		docker build -t $image_name .
		docker push $image_name
	)
done
