#!/bin/bash

set -x

DOCKER_HUB_REPO_NAME=${DOCKER_HUB_REPO_NAME:-mlaventure}

for img in $(find images -type f -name Dockerfile)
do
	dir=$(dirname $img)
	(
		cd $dir
		image_name=${DOCKER_HUB_REPO_NAME}/docker-test-install-from-repo-on-$(basename $dir)
		docker build -t $image_name .
		docker push $image_name
	)
done
